### **Załadowanie bibliotek**

In [ ]:
import pandas as pd

### **Wczytanie danych**

In [ ]:
plik_1 = pd.read_excel('1-500000_note_loan_book.xlsx')

In [ ]:
plik_2 = pd.read_excel('500001-1000000_note_loan_book.xlsx')

In [ ]:
plik_3 = pd.read_excel('1000001-1500000_note_loan_book.xlsx')

In [ ]:
plik_1.head()

,Id,Issue Date,Closing Date,Listing Date,Country,Loan Originator,Mintos Risk Score,Loan Type,Loan Rate Percent,Term,...,Buyback reason,Initial Loan Amount,Remaining Loan Amount,Available for investments,Currency,Buyback,Extendable schedule,Loan Originator Status,In Recovery,ISIN
0,50333604-01,2022-05-28 00:00:00,2023-09-29 00:00:00,2022-05-30 15:39:08,Latvia,Banknote,8.6,Personal Loan,14.5,16,...,Agreement amendment,677.98,0.0,0.0,EUR,Yes,No,Active,No,LVX000000Y74
1,50336144-01,2021-08-06 00:00:00,2026-11-08 00:00:00,2022-05-30 12:34:31,Lithuania,Placet,8.0,Personal Loan,10.0,54,...,Early repayment,5000.00,0.0,0.0,EUR,Yes,Yes,Active,No,LVX000000VD0
2,50336154-01,2021-08-19 00:00:00,2026-10-22 00:00:00,2022-05-30 12:34:31,Lithuania,Placet,8.0,Personal Loan,10.0,54,...,Early repayment,5000.00,0.0,0.0,EUR,Yes,Yes,Active,No,LVX000000VD0
3,50336155-01,2021-08-19 00:00:00,2026-12-21 00:00:00,2022-05-30 12:34:31,Lithuania,Placet,8.0,Personal Loan,10.0,56,...,Early repayment,4350.00,0.0,0.0,EUR,Yes,Yes,Active,No,LVX000000VD0
4,50336157-01,2021-09-01 00:00:00,2026-08-06 00:00:00,2022-05-30 12:34:31,Lithuania,Placet,8.0,Personal Loan,10.0,50,...,Early repayment,4000.00,0.0,0.0,EUR,Yes,Yes,Active,No,LVX000000VD0

### **Przegląd danych**

In [ ]:
plik_1["Loan Status"].unique()

array(['Finished prematurely', 'Current', 'Late 1-15',
       'Finished as scheduled', 'Late 16-30', 'Late 31-60',
       'Grace Period', 'Late 60+'], dtype=object)

In [ ]:
plik_1["Buyback reason"].unique()

array(['Agreement amendment', 'Early repayment', '-', 'Buyback',
       'Agreement prolongation', 'Other', 'Agreement termination'],
      dtype=object)

In [ ]:
plik_1.dtypes

Id                            object
Issue Date                    object
Closing Date                  object
Listing Date                  object
Country                       object
Loan Originator               object
Mintos Risk Score             object
Loan Type                     object
Loan Rate Percent            float64
Term                           int64
Collateral                    object
Initial LTV                    int64
LTV                            int64
Loan Status                   object
Buyback reason                object
Initial Loan Amount          float64
Remaining Loan Amount        float64
Available for investments    float64
Currency                      object
Buyback                       object
Extendable schedule           object
Loan Originator Status        object
In Recovery                   object
ISIN                          object
dtype: object

**Usunięcie rekordów, dla których "Loan Status" = 'Current', 'Late 1-15', 'Late 16-30', 'Late 31-60', 'Grace Period', 'Late 60+'**

In [ ]:
plik_1 = plik_1[~plik_1["Loan Status"].isin(["Current", "Late 1-15", "Late 16-30", "Late 31-60", "Grace Period", "Late 60+"])]

In [ ]:
len(plik_1)

250264

In [ ]:
plik_2 = plik_2[~plik_2["Loan Status"].isin(["Current", "Late 1-15", "Late 16-30", "Late 31-60", "Grace Period", "Late 60+"])]

In [ ]:
len(plik_2)

221555

In [ ]:
plik_3 = plik_3[~plik_3["Loan Status"].isin(["Current", "Late 1-15", "Late 16-30", "Late 31-60", "Grace Period", "Late 60+"])]

In [ ]:
len(plik_3)

66652

### **Połączenie danych w jeden DataFrame**

In [ ]:
dane = pd.concat([plik_1, plik_2, plik_3], ignore_index=True)

In [ ]:
print(dane.shape)

(538471, 24)

In [ ]:
dane.to_csv("dane.csv", index=False)